
package org.soap.proxy.reservations;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ReservationWebServiceService", targetNamespace = "http://server.reservation.org/", wsdlLocation = "http://localhost:8088/reservations?wsdl")
public class ReservationWebServiceService
    extends Service
{

    private static final URL RESERVATIONWEBSERVICESERVICE_WSDL_LOCATION;
    private static final WebServiceException RESERVATIONWEBSERVICESERVICE_EXCEPTION;
    private static final QName RESERVATIONWEBSERVICESERVICE_QNAME = new QName("http://server.reservation.org/", "ReservationWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/reservations?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESERVATIONWEBSERVICESERVICE_WSDL_LOCATION = url;
        RESERVATIONWEBSERVICESERVICE_EXCEPTION = e;
    }

    public ReservationWebServiceService() {
        super(__getWsdlLocation(), RESERVATIONWEBSERVICESERVICE_QNAME);
    }

    public ReservationWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESERVATIONWEBSERVICESERVICE_QNAME, features);
    }

    public ReservationWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, RESERVATIONWEBSERVICESERVICE_QNAME);
    }

    public ReservationWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESERVATIONWEBSERVICESERVICE_QNAME, features);
    }

    public ReservationWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReservationWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Reservations
     */
    @WebEndpoint(name = "ReservationsPort")
    public Reservations getReservationsPort() {
        return super.getPort(new QName("http://server.reservation.org/", "ReservationsPort"), Reservations.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Reservations
     */
    @WebEndpoint(name = "ReservationsPort")
    public Reservations getReservationsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.reservation.org/", "ReservationsPort"), Reservations.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESERVATIONWEBSERVICESERVICE_EXCEPTION!= null) {
            throw RESERVATIONWEBSERVICESERVICE_EXCEPTION;
        }
        return RESERVATIONWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
