
package org.soap.proxy.books;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Books", targetNamespace = "http://server.reservation.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Books {


    /**
     * 
     * @param book
     * @return
     *     returns org.soap.proxy.books.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBook", targetNamespace = "http://server.reservation.org/", className = "org.soap.proxy.books.GetBook")
    @ResponseWrapper(localName = "getBookResponse", targetNamespace = "http://server.reservation.org/", className = "org.soap.proxy.books.GetBookResponse")
    @Action(input = "http://server.reservation.org/Books/getBookRequest", output = "http://server.reservation.org/Books/getBookResponse")
    public Book getBook(
        @WebParam(name = "Book", targetNamespace = "")
        Integer book);

    /**
     * 
     * @return
     *     returns java.util.List<org.soap.proxy.books.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBooks", targetNamespace = "http://server.reservation.org/", className = "org.soap.proxy.books.GetAllBooks")
    @ResponseWrapper(localName = "getAllBooksResponse", targetNamespace = "http://server.reservation.org/", className = "org.soap.proxy.books.GetAllBooksResponse")
    @Action(input = "http://server.reservation.org/Books/getAllBooksRequest", output = "http://server.reservation.org/Books/getAllBooksResponse")
    public List<Book> getAllBooks();

    /**
     * 
     * @param book
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteBook", targetNamespace = "http://server.reservation.org/", className = "org.soap.proxy.books.DeleteBook")
    @ResponseWrapper(localName = "deleteBookResponse", targetNamespace = "http://server.reservation.org/", className = "org.soap.proxy.books.DeleteBookResponse")
    @Action(input = "http://server.reservation.org/Books/deleteBookRequest", output = "http://server.reservation.org/Books/deleteBookResponse")
    public boolean deleteBook(
        @WebParam(name = "Book", targetNamespace = "")
        Integer book);

    /**
     * 
     * @param book
     * @return
     *     returns org.soap.proxy.books.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateBook", targetNamespace = "http://server.reservation.org/", className = "org.soap.proxy.books.UpdateBook")
    @ResponseWrapper(localName = "updateBookResponse", targetNamespace = "http://server.reservation.org/", className = "org.soap.proxy.books.UpdateBookResponse")
    @Action(input = "http://server.reservation.org/Books/updateBookRequest", output = "http://server.reservation.org/Books/updateBookResponse")
    public Book updateBook(
        @WebParam(name = "Book", targetNamespace = "")
        Book book);

    /**
     * 
     * @param book
     * @return
     *     returns org.soap.proxy.books.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addBook", targetNamespace = "http://server.reservation.org/", className = "org.soap.proxy.books.AddBook")
    @ResponseWrapper(localName = "addBookResponse", targetNamespace = "http://server.reservation.org/", className = "org.soap.proxy.books.AddBookResponse")
    @Action(input = "http://server.reservation.org/Books/addBookRequest", output = "http://server.reservation.org/Books/addBookResponse")
    public Book addBook(
        @WebParam(name = "Book", targetNamespace = "")
        Book book);

}
